Repository ckb-js/nexus, pull requests merged in 2023-04, with the labels that each got.

#187 feat(extension-chrome): optimize displaying amount of asset
  package-lock.json
  package.json
  packages/extension-chrome/src/pages/Notification/containers/SignTransaction.tsx
Labels: patch, skip-release

#183 fix: getLiveCells returns specified change type cells
  packages/extension-chrome/__tests__/services/ownership/fullOwnership.test.ts
  packages/extension-chrome/src/services/ownership/fullOwnership.ts
Labels: patch, skip-release

#145 docs: run a dev CKB blockchain
  docs/assets/add-network-info.png
  docs/assets/add-network.png
  docs/assets/derived-locks.png
  docs/assets/tree.png
  docs/run-dev-ckb-blockchain.md
Labels: documentation

#184 test: e2e test scaffolding
  .github/workflows/e2e.yaml
  e2e/.eslintrc.js
  e2e/.gitignore
  e2e/README.md
  e2e/constants/index.ts
  e2e/helpers/DefaultTestEnv.ts
  e2e/helpers/index.ts
  e2e/helpers/storage.ts
  e2e/jest.config.ts
  e2e/package.json
  e2e/tests/wallet-enable.test.ts
  e2e/tsconfig.json
  package-lock.json
  package.json
Labels: internal

#194 refactor: make utils flatten
  package-lock.json
  package.json
  packages/extension-chrome/package.json
  packages/extension-chrome/src/services/keystore/keystore.ts
  packages/types/src/base.ts
  packages/types/src/services/KeystoreService.ts
  packages/types/src/services/common.ts
  packages/utils/__tests__/asserts.ts
  packages/utils/__tests__/error.ts
  packages/utils/__tests__/internal.ts
  packages/utils/package.json
  packages/utils/src/asserts.ts
  packages/utils/src/asyncSleep.ts
  packages/utils/src/env.ts
  packages/utils/src/error.ts
  packages/utils/src/index.ts
  packages/utils/src/internal/format.ts
  packages/utils/src/internal/index.ts
  packages/utils/src/internal/resolve.ts
  packages/utils/src/logger.ts
Labels: internal

#210 chore: bump manifest version in ci
  .eslintrc.js
  package.json
  packages/utils/package.json
  scripts/update-version.ts
Labels: patch

#212 chore: avoid canary for renovate pr
  renovate.json
Labels: internal

#208 chore: add eslint import plugin
  .eslintrc.js
  package-lock.json
  package.json
  packages/extension-chrome/__tests__/services/ownership/fullOwnership.test.ts
  packages/extension-chrome/package.json
  packages/extension-chrome/src/mockServices/config.ts
  packages/extension-chrome/src/pages/Notification/utils/WellkownCellManager.tsx
  packages/extension-chrome/src/pages/Popup/containers/Home.tsx
  packages/extension-chrome/src/pages/WalletManager/containers/NewMnemonic.tsx
  packages/extension-chrome/src/pages/WalletManager/containers/RecoveryWallet.tsx
  packages/extension-chrome/src/pages/WalletManager/containers/Welcome.tsx
  packages/extension-chrome/src/services/ownership/backend/index.ts
  packages/ownership-providers/__tests__/FullOwnershipProvider.test.ts
Labels: internal

#189 feat: serial notif windows to avoid confusion from multiple notif
  package-lock.json
  packages/extension-chrome/__tests__/rpc/wallet.test.ts
  packages/extension-chrome/__tests__/services/config.test.ts
  packages/extension-chrome/package.json
  packages/extension-chrome/src/errors/list.ts
  packages/extension-chrome/src/pages/hooks/useSessionMessenger.ts
  packages/extension-chrome/src/rpc/walletImpl.ts
  packages/extension-chrome/src/services/config.ts
  packages/extension-chrome/src/services/factory/index.ts
  packages/extension-chrome/src/services/notification/common.ts
  packages/extension-chrome/src/services/notification/index.ts
  packages/extension-chrome/src/services/notification/notificationManager.ts
Labels: minor

#216 feat: badge to show how many notif window is pending
  packages/extension-chrome/src/services/notification/notificationManager.ts
Labels: minor, skip-release

#209 chore: update webext-bridge to v6
  .eslintrc.js
  package-lock.json
  packages/extension-chrome/package.json
  packages/extension-chrome/src/background/main.ts
  packages/extension-chrome/src/contentScript/content.ts
  packages/extension-chrome/src/services/event/extension.ts
Labels: skip-release, internal

#244 fix: network changed event does'n trigger
  packages/extension-chrome/src/contentScript/content.ts
  packages/extension-chrome/src/mockServices/config.ts
  packages/extension-chrome/src/mockServices/types.ts
  packages/extension-chrome/src/pages/Popup/containers/Network/NetworkConfig.tsx
  packages/extension-chrome/src/services/event/extension.ts
  packages/extension-chrome/tsconfig.json
Labels: patch

#161 feat(testkit): a testkit pkg for unit test
  package-lock.json
  packages/testkit/README.md
  packages/testkit/examples/ckb.ts
  packages/testkit/package.json
  packages/testkit/src/generate.ts
  packages/testkit/src/index.ts
  packages/testkit/src/mockInjectedCkb.ts
  packages/testkit/src/random.ts
  packages/testkit/tsconfig.json
Labels: skip-release, tests

#227 feat(extension-chrome): support send transaction
  docs/rpc.md
  package.json
  packages/extension-chrome/__tests__/helpers/mockBackend.ts
  packages/extension-chrome/__tests__/rpc/ckb.test.ts
  packages/extension-chrome/__tests__/rpc/helper.ts
  packages/extension-chrome/__tests__/services/ownership/backend/backend.test.ts
  packages/extension-chrome/src/rpc/ckbImpl.ts
  packages/extension-chrome/src/rpc/schema/blockchain.ts
  packages/extension-chrome/src/rpc/schema/index.ts
  packages/extension-chrome/src/services/ownership/backend/backendUtils.ts
  packages/extension-chrome/src/services/ownership/backend/index.ts
  packages/protocol/src/base.ts
  packages/protocol/src/ckb.ts
Labels: minor, skip-release

#253 fix(extension-chrome): receiving end does not exist
  packages/extension-chrome/src/services/event/extension.ts
Labels: patch

#152 docs: nexus works with custody unlocking
  docs/custody-unlocking.md
Labels: documentation

#249 feat(detect-ckb): a module for detecting injected ckb
  package-lock.json
  packages/detect-ckb/README.md
  packages/detect-ckb/__tests__/detect.ts
  packages/detect-ckb/jest.config.js
  packages/detect-ckb/package.json
  packages/detect-ckb/src/index.ts
  packages/detect-ckb/tsconfig.json
  packages/detect-ckb/tsconfig.test.json
Labels: minor, skip-release

#251 fix(ownership-providers): inject witness and cellDeps auto
  packages/ownership-providers/__tests__/FullOwnershipProvider.test.ts
  packages/ownership-providers/jest.config.js
  packages/ownership-providers/src/FullOwnershipProvider.ts
  packages/ownership-providers/tsconfig.json
  packages/ownership-providers/tsconfig.test.json
Labels: patch, skip-release

#252 chore: example for using ownership provider in a dapp
  .eslintrc.js
  .gitignore
  babel.config.json
  examples/.gitignore
  examples/transfer-with-provider/index.html
  examples/transfer-with-provider/package.json
  examples/transfer-with-provider/src/App.tsx
  examples/transfer-with-provider/src/hooks/useAsyncState.ts
  examples/transfer-with-provider/src/hooks/useEnable.ts
  examples/transfer-with-provider/src/hooks/useProvider.tsx
  examples/transfer-with-provider/src/main.tsx
  examples/transfer-with-provider/tsconfig.json
  examples/transfer/package.json
  package-lock.json
  package.json
  packages/detect-ckb/__tests__/detect.ts
  packages/detect-ckb/package.json
  packages/extension-chrome/config/webpack.config.common.ts
  packages/extension-chrome/package.json
Labels: skip-release, internal

#255 feat(ownership-provider): supported send transaction
  examples/transfer-with-provider/src/App.tsx
  examples/transfer/package.json
  packages/ownership-providers/__tests__/FullOwnershipProvider.test.ts
  packages/ownership-providers/src/FullOwnershipProvider.ts
Labels: minor, skip-release

#256 docs: developer tutorial
  README.md
  docs/get-started.md
  docs/tutorial-assets/init.png
  docs/tutorial-assets/nexus-sign-tx.png
  docs/tutorial-assets/switch-to-testnet.png
  docs/tutorial-assets/tutorial.excalidraw
  docs/tutorial-assets/tx-empty.png
  docs/tutorial-assets/tx-injected.png
  docs/tutorial-assets/tx-paid.png
  docs/tutorial-assets/tx-sent.png
  docs/tutorial-assets/tx-setup-receiver.png
  docs/tutorial.md
Labels: documentation

#274 chore: move testkit to devDependencies
  package-lock.json
  packages/extension-chrome/package.json
Labels: internal

#273 refactor(e2e): make the config more clear
  e2e/README.md
  e2e/helpers/CkbNode.ts
  e2e/helpers/index.ts
  e2e/tests/CkbNode.test.ts
Labels: tests

#269 chore: fix incorrect coverage in code cov
  .github/workflows/e2e.yaml
  .github/workflows/main.yaml
  CHANGELOG.md
  jest.config.js
  package-lock.json
  package.json
  packages/detect-ckb/CHANGELOG.md
  packages/extension-chrome/__tests__/services/ownership/daemonWatchtower.test.ts
  packages/extension-chrome/public/manifest.json
  packages/ownership-providers/CHANGELOG.md
Labels: skip-release, tests
