Repository ckb-js/nexus, pull requests merged in 2023-05, with the labels that each got.

#272 feat(ownership-provider): support `payFee` and `signTransaction` in `sendTransaction`
  examples/transfer-with-provider/src/App.tsx
  package-lock.json
  packages/ownership-providers/__tests__/FullOwnershipProvider.test.ts
  packages/ownership-providers/src/FullOwnershipProvider.ts
  packages/ownership-providers/src/types.ts
  packages/ownership-providers/src/utils.ts
Labels: minor

#276 chore: fix release error in pipeline
  .husky/pre-commit
  package.json
Labels: internal

#280 test: Fix e2e timeout
  e2e/helpers/DefaultTestEnv.ts
  e2e/package.json
  e2e/tests/wallet-enable.test.ts
Labels: internal

#9 docs: design of Nexus
  docs/design-anyone-can-pay.md
  docs/design.md
  docs/design/omnilock-p2sh-acp.excalidraw
  docs/design/omnilock-p2sh-acp.png
  docs/design/p2pkh.excalidraw
  docs/design/p2pkh.png
  docs/design/p2sh.excalidraw
  docs/design/p2sh.png
  docs/purpose-field.md
Labels: documentation, skip-release

#4 docs: proposal for Nexus
  docs/assets/approve-tx.excalidraw
  docs/assets/approve-tx.png
  docs/assets/nexus-arch.excalidraw
  docs/assets/nexus-arch.png
  docs/assets/opentx.excalidraw
  docs/assets/opentx.png
  docs/assets/overview.excalidraw
  docs/assets/overview.png
  docs/assets/sign-eip191.png
  docs/assets/sign-eip712.png
  docs/assets/sign-tron.png
  docs/assets/utxo-transfer-example.excalidraw
  docs/assets/utxo-transfer-example.png
  docs/proposal.md
Labels: documentation, skip-release

#240 docs: view logs and dump state
  docs/assets/dump-state.png
  docs/assets/show-devtools.png
  docs/contributing/development.md
  docs/contributing/pull-request.md
  docs/development.md
  docs/faq.md
Labels: documentation, skip-release
