Repository ckb-js/nexus, pull requests merged in 2023-03, with the labels that each got.

#140 chore: bypass protect branch
  .github/workflows/main.yaml
  package-lock.json
  package.json
Labels: internal

#147 chore: prevent canary release in PR from forked repo
  .github/workflows/main.yaml
Labels: internal

#139 feat: sign data with a magic prefix for security
  package-lock.json
  packages/extension-chrome/__tests__/services/ownership/fullOwnership.test.ts
  packages/extension-chrome/package.json
  packages/extension-chrome/src/services/ownership/fullOwnership.ts
  packages/protocol/package.json
Labels: breaking-minor

#150 docs: faq
  docs/faq.md
Labels: documentation

#138 refactor: disable unsafe any access
  .eslintrc.js
  packages/extension-chrome/src/background/main.ts
  packages/extension-chrome/src/contentScript/content.ts
  packages/extension-chrome/src/messaging/contentAndInjected.ts
  packages/extension-chrome/src/messaging/session.ts
  packages/extension-chrome/src/rpc/middlewares/parameterValidateMiddleware.ts
  packages/extension-chrome/src/services/ownership/backend/thirdpartyLib/p-retry.ts
  packages/extension-chrome/src/services/ownership/backend/thirdpartyLib/p-timeout.ts
  packages/extension-chrome/src/services/storage/memory.ts
Labels: internal

#157 fix: connect status is always connected
  packages/extension-chrome/__tests__/helpers/mockPlatformService.ts
  packages/extension-chrome/src/pages/Components/ConnectStatusCard.tsx
  packages/extension-chrome/src/pages/Components/icons/MinusCircle.svg
  packages/extension-chrome/src/pages/Popup/containers/Home.tsx
  packages/extension-chrome/src/pages/Popup/containers/WhitelistSites.tsx
  packages/extension-chrome/src/pages/hooks/useService.ts
  packages/extension-chrome/src/services/notification.ts
  packages/types/src/services/NotificationService.ts
Labels: patch

#167 fix: retry not work in backend
  packages/extension-chrome/__tests__/services/ownership/backend/backendUtil.test.ts
  packages/extension-chrome/src/services/ownership/backend/backendUtils.ts
Labels: patch

#175 docs: new readme
  README.md
Labels: documentation

#174 fix(extension-chrome): enable for http and local site
  package-lock.json
  packages/extension-chrome/__tests__/utils/validate.test.ts
  packages/extension-chrome/src/contentScript/content.ts
  packages/extension-chrome/src/contentScript/inpage.ts
  packages/extension-chrome/src/services/config.ts
  packages/extension-chrome/src/utils/validate.ts
  packages/types/src/services/NotificationService.ts
  packages/utils/package.json
Labels: patch, skip-release

#173 chore(extension-chrome): remove unnecessary accessible
  packages/extension-chrome/public/manifest.json
Labels: patch, skip-release

#168 feat: supported get blockchain info rpc
  docs/rpc.md
  packages/extension-chrome/__tests__/helpers/mockBackend.ts
  packages/extension-chrome/__tests__/services/ownership/backend/backend.test.ts
  packages/extension-chrome/src/background/main.ts
  packages/extension-chrome/src/rpc/ckbImpl.ts
  packages/extension-chrome/src/services/ownership/backend/index.ts
  packages/protocol/src/ckb.ts
  packages/protocol/src/event.ts
  packages/protocol/src/rpc.ts
  packages/types/src/services/ConfigService.ts
  packages/types/src/services/EventService.ts
  packages/types/src/services/index.ts
Labels: minor
